package kg.zhoodar.base.yandex.api.business;


import kg.zhoodar.base.yandex.api.model.YaPage;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.XMLReader;
import org.xml.sax.helpers.XMLReaderFactory;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLEncoder;


public class YaSearcher {

    private static final String YA_URL = "https://yandex.com/search/xml?l10n=en&";
    private static final String ENC = "UTF-8";
    private static final String AND = "&";

    private String user;
    private String key;

    /**
     * Constructor
     * @param user your Yandex username
     * @param key key generated by Yandex.XML
     */
    public YaSearcher(final String user, final String key) {
        this.user = user;
        this.key = key;
    }

    /**
     * Retrieve Yandex.XML response stream via GET request
     * @param query search query
     * @param pageNumber number of search page
     * @return Yandex.XML response stream
     * @throws IOException input/output exception
     */
    public InputStream retrieveResponseViaGetRequest(
            final String query,
            final int pageNumber
    ) throws IOException {

        final StringBuilder address = new StringBuilder(YA_URL);
        address.append("user=").append(user).append(AND)
                .append("key=").append(key).append(AND)
                .append("query=").append(URLEncoder.encode(query, ENC)).append(AND)
                .append("page=").append(pageNumber);
        final URL url = new URL(address.toString());
        return url.openStream();
    }

    /**
     * Load parsed yandex page from Yandex.XML service
     * @param query query for searching
     * @param pageNumber number of page
     * @return parsed result of searching
     * @throws IOException input/output exception
     * @throws SAXException parsing exception
     */
    public YaPage loadYaPage(final String query, final int pageNumber)
            throws IOException, SAXException {

        final YaPage result = new YaPage(query, pageNumber);
        final XMLReader xmlReader = XMLReaderFactory.createXMLReader();
        xmlReader.setContentHandler(new YaHandler(result));
        xmlReader.parse(
                new InputSource(
                        this.retrieveResponseViaGetRequest(query, pageNumber)
                )
        );
        return result;
    }

}